# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?

Member.create!(name: 'Patti')
Member.create!(name: 'Katze')
Member.create!(name: 'Celo')
Member.create!(name: 'Joel')
Member.create!(name: 'Christian')
Member.create!(name: 'Unni')
Member.create!(name: 'Darvin')
Member.create!(name: 'Zachi')
Member.create!(name: 'Horst')
Member.create!(name: 'Ingo')
Member.create!(name: 'Jan')
Member.create!(name: 'Jansi')
Member.create!(name: 'Jens')
Member.create!(name: 'Finch')
Member.create!(name: 'Dete')
Member.create!(name: 'Julian')
Member.create!(name: 'Ken')
Member.create!(name: 'Lennert')
Member.create!(name: 'Luca')
Member.create!(name: 'Marius')
Member.create!(name: 'Matze')
Member.create!(name: 'Max')
Member.create!(name: 'Moritz')
Member.create!(name: 'Kocki')
Member.create!(name: 'Hecki')
Member.create!(name: 'Janji')
Member.create!(name: 'Ricardo')
Member.create!(name: 'Robin')
Member.create!(name: 'Romeo')
Member.create!(name: 'Tahir')
Member.create!(name: 'Schaddi')
Member.create!(name: 'Tino')
Member.create!(name: 'Tobi')
Member.create!(name: 'Bulle')

Penalty.create!(penalty_name: 'tunnel', penalty_cost: 1, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'tunnelhacke', penalty_cost: 2, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'kontakte15', penalty_cost: 1, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'kontakt14verkackt', penalty_cost: 2, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'ball1verkackt', penalty_cost: 1, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'ball1verhindert', penalty_cost: 1, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'ball1tunnel', penalty_cost: 1, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'ballinstor', penalty_cost: 1, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'rotekartebeleidigung', penalty_cost: 25, case_of_beer_cost: 1)
Penalty.create!(penalty_name: 'platzverweismeckern', penalty_cost: 50, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'gelbekartemeckern', penalty_cost: 10, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'trainerhinterbande', penalty_cost: 25, case_of_beer_cost: 1)
Penalty.create!(penalty_name: 'unentschuldigtspiel', penalty_cost: 50, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'unentschuldigttraining', penalty_cost: 10, case_of_beer_cost: 1)
Penalty.create!(penalty_name: 'abmeldungingruppe', penalty_cost: 5, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'alkoholisiertzumspiel', penalty_cost: 50, case_of_beer_cost: 1)
Penalty.create!(penalty_name: 'sieg', penalty_cost: 15, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'unentschieden', penalty_cost: 6, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'pflichtspielverloren', penalty_cost: 2, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'sachenvergessen', penalty_cost: 2, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'teilevontrikotsatzvergessen', penalty_cost: 5, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'falschereinwurf', penalty_cost: 2, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'torschussinsseitenaus', penalty_cost: 0, case_of_beer_cost: 1)
Penalty.create!(penalty_name: 'evakuierungkabine', penalty_cost: 15, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'abartigfurzen', penalty_cost: 5, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'übernzaunschießen', penalty_cost: 2, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'schussauftennisplatz', penalty_cost: 2, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'foto', penalty_cost: 1, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'pinkelninderdusche', penalty_cost: 5, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'asozialesverhalten', penalty_cost: 5, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'nichtbeimspielgucken', penalty_cost: 10, case_of_beer_cost: 0)
Penalty.create!(penalty_name: 'geburtstagswünschegruppe', penalty_cost: 5, case_of_beer_cost: 0)